#!/usr/bin/python
# -*- coding: utf-8 -*-

# Screenja - Efficient OSX Screenshot taking for work
# Autor: Tomas Dobrotka : tomas@dobrotka.sk | www.dobrotka.sk
# https://github.com/ggtd/Screenja

APP_NAME="Screenja"
APP_VERSION='0.04'
print "Version: "+str(APP_VERSION)

SAVE_SUBDIR='Screenshots'

APP_CONFIG_DEFAULT='Screenshot'
APP_CONFIG_WINDOW_TITLE='Name screenshot'

#first do screenshot ASAP

import os
import time

TMP_IMAGE_FILENAME="/tmp/screenja_tmp.delete."+str(time.time())+".png"

os.system("screencapture  -i "+TMP_IMAGE_FILENAME)

#later do all the rest stuff

from Tkinter import *

HOME_PATH=os.getenv("HOME")


def doquit():
    print "exiting"
    os.system("rm "+TMP_IMAGE_FILENAME)
    quit()




def history():
    print "history......"
    e.pack_forget()
    h_button.pack_forget()
    b_save.pack_forget()
    b_calcel.pack_forget()

    variable = StringVar(master)
    variable.set("one")  # default value
    w = OptionMenu(master, variable, "one", "two", "three")
    w.pack()

    b_save.pack()

    bacckk = Button(master, text="< Back", width=10, command=history_back)
    bacckk.pack()


    b_calcel.pack()


    pass

def history_back():
    bacckk.pack_forget()
    w.pack_forget()
    e.pack()
    b_save.pack()
    h_button.pack()
    b_calcel.pack()



def save():
    NAME_RAW=str(e.get())
    NAME=NAME_RAW.replace(' ','_')
    FOLDER = 'Screenshots'
    if NAME<>"":FOLDER=NAME
    if NAME=="": NAME='Screenshot'
    FILE_NAME=NAME+"_"+time.strftime('%Y-%m-%d_%H-%M-%S')
    print "Name: "+NAME
    print "save..."
    f = open(HOME_PATH+"/.screenja.last.screen.name", 'w')
    f.write(str(NAME_RAW))
    f.close()

    os.system("mkdir ~/Desktop/"+SAVE_SUBDIR+'/'+FOLDER+"/")
    os.system("mv "+TMP_IMAGE_FILENAME+" ~/Desktop/"+SAVE_SUBDIR+'/'+FOLDER+"/"+FILE_NAME+".png")
    quit()

master = Tk()


master.title(APP_CONFIG_WINDOW_TITLE)
master.attributes("-topmost", True)
master.lift()



try:
    with open(HOME_PATH+"/.screenja.last.screen.name", "r") as f:
        IMPUT_VALUE=f.readline()
except:
    IMPUT_VALUE=APP_CONFIG_DEFAULT


e = Entry(master)
e.pack()
e.insert(0, IMPUT_VALUE)
e.focus_set()

b_save = Button(master, text="Save", width=10, command=save)
b_save.pack()


h_button = Button(master, text="History", width=10, command=history)
h_button.pack()

from PIL import Image, ImageTk


image = Image.open(TMP_IMAGE_FILENAME)
img_width, img_height = image.size
print img_width
print img_height

new_img_width=400
new_img_height=img_height/float(img_width)
new_img_height=new_img_height*new_img_width
print new_img_height

image = image.resize((int(new_img_width),int(new_img_height)), Image.ANTIALIAS)

display = ImageTk.PhotoImage(image)

label = Label(master, image=display,height=300, width=300)
label.pack()


b_calcel = Button(master, text="Cancel", width=10,command=doquit)
b_calcel.pack()
e.focus_set()


master.mainloop()

